model:
  name: yolov8
  variant: yolov8n  # 使用较小的模型以适应CPU训练
  pretrained: true
  device: cpu
  num_classes: 1

data:
  train_path: data/dataset/train_data
  val_path: data/dataset/test_data
  img_size: 512
  batch_size: 8
  workers: 2

train:
  epochs: 20
  lr0: 0.001
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 2
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  project: experiments/yolo  # 指定保存目录
  name: exp  # 实验名称

val:
  conf_thres: 0.25
  iou_thres: 0.5
  max_det: 300 