# 实验配置文件
model:
  name: null  # 将由具体实验配置指定
  variant: null  # 将由具体实验配置指定
  encoder_name: null  # 将由具体实验配置指定
  encoder_weights: imagenet
  in_channels: 3
  classes: 1
  num_classes: 1
  activation: sigmoid
  pretrained: true
  device: cpu

data:
  train_path: data/dataset/train_data
  val_path: data/dataset/test_data
  img_size: 512
  batch_size: 8
  workers: 2

train:
  epochs: 20  # 增加到20轮以获得更好的效果
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 2
    min_lr: 0.0001
  loss:
    name: BCEWithLogitsLoss
  # YOLO特定参数
  lr0: 0.001
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 2
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

val:
  metrics:
    - iou_score
    - f1_score
    - accuracy
    - precision
    - recall
  threshold: 0.5
  conf_thres: 0.25  # 调整为与融合模型相同的阈值
  iou_thres: 0.5
  max_det: 300

augmentation:
  train:
    - name: HorizontalFlip
      p: 0.5
    - name: VerticalFlip
      p: 0.5
    - name: RandomRotate90
      p: 0.5
    - name: RandomBrightnessContrast
      p: 0.3
    - name: GaussNoise
      p: 0.2
  val:
    - name: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

save:
  dir: experiments
  checkpoint_interval: 5  # 每5轮保存一次检查点 