model:
  name: yolov8
  variant: yolov8n  # 使用最小的模型
  pretrained: true
  num_classes: 1    # PCB缺陷检测类别数
  device: cpu       # 使用CPU训练

data:
  train_path: data/dataset/train_data
  val_path: data/dataset/test_data
  img_size: 416    # 减小图像尺寸
  batch_size: 4    # 减小batch size
  workers: 2       # 减少工作进程数

train:
  epochs: 3        # 减少训练轮次
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 0  # 关闭预热
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

val:
  conf_thres: 0.001
  iou_thres: 0.6
  max_det: 300

augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.0     # 关闭mosaic增强
  mixup: 0.0 